---
- hosts: all

  tasks:
  - name: create user for AUR
    user:
      name: aur_builder
      group: wheel

  - name: change sudoers
    lineinfile:
      become: yes
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'


