---
- hosts: all

  tasks:
    - name: install i3 tiling windows manager
      become: yes
      package:
        name: i3-wm
        state: present

    - name: install addons for i3wm
      become: yes
      pacman:
        name: rofi, feh, i3status
        state: present
        #update_cache: yes

    - name: install System San Francisco Font
      aur: name=system-san-francisco-font-git use=makepkg skip_installed=true
      become: yes
      become_user: melsior

    - file:
        dest: ~/.config/i3
        state: directory

    - file:
        src: "{{ curdir }}/files/i3config"
        dest: ~/.config/i3/config
        state: link

    - name: configuration of Qt5 apps
      become: yes
      pacman:
        name: qt5ct
        state: present

    - file:
        src: "{{ curdir }}/files/xprofile"
        dest: $HOME/.xprofile
        state: link
