---
- hosts: all

  tasks:
    - name: install kitty terminal emulator
      become: yes
      package:
        name: kitty
        state: present


    - name: configure kitty terminale emulator
      file:
        dest: $HOME/.config/kitty
        state: directory

      file:
        src: "{{ curdir }}/files/kitty.conf"
        dest: ~/.config/kitty/kitty.conf
        state: link
    
    - name: change color scheme to solarized dark patched
      file:
        src: "{{ curdir }}/files/kitty-themes/themes/Solarized_Dark_-_Patched.conf"
        dest: ~/.config/kitty/theme.conf
        state: link

