---

- hosts: localhost

  tasks:
        - file:
                path: $HOME/.config/nvim
                state: directory

        - file:
                src: $HOME/dotfiles/files/vimrc
                dest: $HOME/.config/nvim/init.vim
                state: link

