setglobal nocompatible
setglobal pastetoggle=<F2>

set ttyfast
set lazyredraw

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'icymind/neosolarized'
call plug#end()

set termguicolors
set background=dark
colorscheme NeoSolarized 
