setglobal nocompatible
setglobal pastetoggle=<F2>

set ttyfast
set lazyredraw

let g:python_host_skip_check=1
let g:loaded_python3_provider=1

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'icymind/neosolarized'
Plug 'ierton/xkb-switch'
call plug#end()

set termguicolors
set background=dark
colorscheme NeoSolarized
let g:XkbSwitchEnabled = 1
let g:XkbSwitchIMappings = ['ru']
